package psl.chime4.server.ces;

/**
 * Represents a generic exception for an exception generated by the event
 * service.
 *
 * @author Azubuko Obele
 * @version 0.1
 **/
public class EventServiceException extends Exception
{
   public EventServiceException()
   {
      super();
   }
   
   public EventServiceException(String msg)
   {
      super(msg);
   }
   
   public EventServiceException(String msg, Throwable cause)
   {
      super(msg, cause);
   }
   
   public EventServiceException(Throwable cause)
   {
      super(cause);
   }
}
